
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 09 11:26:49 EET 2016
//----------------------------------------------------

package frontend.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUB_OP = 8;
  public static final int MUL_OP = 9;
  public static final int LT_OP = 18;
  public static final int COND = 23;
  public static final int LPAREN = 27;
  public static final int ADD_OP = 7;
  public static final int RBRAC = 30;
  public static final int FOR = 34;
  public static final int GE_OP = 17;
  public static final int RPAREN = 28;
  public static final int SUB_ASSIGN = 3;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int NE_OP = 15;
  public static final int OR = 21;
  public static final int COMMA = 26;
  public static final int GT_OP = 16;
  public static final int IF = 31;
  public static final int AND_OP = 12;
  public static final int ADD_ASSIGN = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int WEND = 33;
  public static final int DIV_ASSIGN = 5;
  public static final int COLON = 24;
  public static final int EQEQ_OP = 14;
  public static final int AND_ASSIGN = 6;
  public static final int EQ_OP = 13;
  public static final int WHILE = 32;
  public static final int POW_OP = 11;
  public static final int DIV_OP = 10;
  public static final int DOLLAR = 25;
  public static final int MUL_ASSIGN = 4;
  public static final int LBRAC = 29;
  public static final int LE_OP = 19;
  public static final int STRING_LIT = 37;
  public static final int INT_LIT = 36;
  public static final int IDENTIFIER = 35;
}

