
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 30 21:03:15 EET 2016
//----------------------------------------------------

package frontend;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int FLOAT_LIT = 5;
  public static final int IDENTIFIER = 2;
  public static final int STRING_LIT = 4;
  public static final int INT_LIT = 3;
  public static final int EOF = 0;
}

